#!/bin/bash

FILE=$1
SESSION=$2
OBJ=$3
URL=$4
IFS=$'\n'
SESSION_OBJS=( $(wget http://objiv-jmerelo.rhcloud.com/get/$SESSION -q -O - ) )  
unset IFS
((OBJ_IDX=OBJ-1))
COMMIT_MSG="${URL} : Añade objetivo #${OBJ} de la sesión ${SESSION}"
echo ${SESSION_OBJS[$OBJ_IDX]/[ ]/X}>>$FILE
git commit -a -m "$COMMIT_MSG"

